### PR TITLE
Apparently the old line was still in there. Took it out.

### PR DESCRIPTION
**Pull request by KrisvanderMast**

### CODE REVIEW

**Comment by maartenba** [comment]
Merge conflicts... Please get latest and try again :-)

**Comment by maartenba** [comment]
@KrisvanderMast please fix

**Comment by maartenba** [comment]
@KrisvanderMast Please fix!

**Comment by maartenba** [comment]
@krisvandermast ping

**Comment by tomkerkhove** [comment]
I can have a look if @KrisvanderMast doesn't have time?

**Comment by tomkerkhove** [comment]
LGTM

**Pull request merged**
